# Generated by Django 3.1.2 on 2020-10-15 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_auto_20201015_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='other_comment', to='network.comment'),
            preserve_default=False,
        ),
    ]
